### PR TITLE
Round without overflow (Fix #59)

### LINKED ISSUE #59: display bug near realmin
```jl
julia> realmin(d64"3.4")
I.nfe+2147483244

julia> realmin(Dec64)
Error showing value of type DecFP.Dec64:
ERROR: BoundsError: attempt to access 326-element Array{UInt8,1} at index [327]
Stacktrace:
 [1] ini_dec(::DecFP.Dec64, ::Int64) at /Users/stevenj/.julia/v0.6/DecFP/src/DecFP.jl:167
 [2] show(::IOContext{Base.Terminals.TTYTerminal}, ::DecFP.Dec64) at /Users/stevenj/.julia/v0.6/DecFP/src/DecFP.jl:75
 [3] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::DecFP.Dec64) at ./REPL.jl:122
 [4] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::DecFP.Dec64) at ./REPL.jl:125
 [5] display(::DecFP.Dec64) at ./multimedia.jl:194
 [6] eval(::Module, ::Any) at ./boot.jl:235
 [7] print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:144
 [8] print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:129
 [9] (::Base.REPL.#do_respond#16{Bool,Base.REPL.##26#36{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:646
```
cc @jmkuhn

### PR DESCRIPTION
**Pull request by jmkuhn**
Fixes #59 
```
julia> @sprintf("%e", realmin(Dec64))
"1.000000e-398"

julia> realmax(Dec64)
9.999999999999999e384

julia> @sprintf("%e", realmax(Dec64))
"1.000000e+385"
```
I uncommented the definitions for `exponent` and `ldexp` and renamed to `exponent10` and `ldexp10` to avoid confusion with Base `exponent` and `ldexp`.  I like the name `scale10` better than `ldexp10`.  Do you have a preference on this?  I am currently using these within `DecFP.jl` but not exporting them.  I also defined `tostring` to wrap the library's `to_string`.  I welcome a better name for this.

### CODE REVIEW

File: src/DecFP.jl [hunk 1]
```diff
@@ -287,8 +294,8 @@ for w in (32,64,128)
         Base.eps(x::$BID) = ifelse(isfinite(x), @xchk(nextfloat(x) - x, OverflowError, "$($BID) value overflow", mask=OVERFLOW), $(_parse(T, "NaN")))
 
         # the meaning of the exponent is different than for binary FP: it is 10^n, not 2^n:
-        # Base.exponent(x::$BID) = nox(ccall(($(bidsym(w,"ilogb")), libbid), Cint, ($BID,), x))
-        # Base.ldexp(x::$BID, n::Integer) = nox(ccall(($(bidsym(w,"ldexp")), libbid), $BID, ($BID,Cint), x, n))
+        exponent10(x::$BID) = nox(ccall(($(bidsym(w,"ilogb")), libbid), Cint, ($BID,), x))
+        ldexp10(x::$BID, n::Integer) = nox(ccall(($(bidsym(w,"ldexp")), libbid), $BID, ($BID,Cint), x, n))
```
Comment (stevengj) [inline src/DecFP.jl]: Should these be exported?

Comment (stevengj) [reply src/DecFP.jl]: Maybe in a separate PR.

Comment (jmkuhn) [reply src/DecFP.jl]: OK. I'll export these in a separate PR.
